; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV32I
; RUN: llc -mtriple=riscv64 -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV64I
; RUN: llc -mtriple=riscv32 -mattr=+zicond -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV32ZICOND
; RUN: llc -mtriple=riscv64 -mattr=+zicond -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV64ZICOND
; RUN: llc -mtriple=riscv64 -mattr=+xventanacondops -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV64XVENTANACONDOPS
; RUN: llc -mtriple=riscv64 -mattr=+zicond,+short-forward-branch-ialu -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefixes=RV64ZICOND-SFB

; Scalar GPR select lowering. Zicond/XVentanaCondOps select a branchless
; czero/vt.maskc sequence; other cores keep the branch-based select.

; select c, t, 0
define i32 @select_t_zero(i1 %c, i32 %t) {
; RV32I-LABEL: select_t_zero:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a2, a0, 1
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    bnez a2, .LBB0_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:  .LBB0_2:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: select_t_zero:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, 1
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    bnez a2, .LBB0_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:  .LBB0_2:
; RV64I-NEXT:    ret
;
; RV32ZICOND-LABEL: select_t_zero:
; RV32ZICOND:       # %bb.0:
; RV32ZICOND-NEXT:    andi a0, a0, 1
; RV32ZICOND-NEXT:    czero.eqz a0, a1, a0
; RV32ZICOND-NEXT:    ret
;
; RV64ZICOND-LABEL: select_t_zero:
; RV64ZICOND:       # %bb.0:
; RV64ZICOND-NEXT:    andi a0, a0, 1
; RV64ZICOND-NEXT:    czero.eqz a0, a1, a0
; RV64ZICOND-NEXT:    ret
;
; RV64XVENTANACONDOPS-LABEL: select_t_zero:
; RV64XVENTANACONDOPS:       # %bb.0:
; RV64XVENTANACONDOPS-NEXT:    andi a0, a0, 1
; RV64XVENTANACONDOPS-NEXT:    vt.maskc a0, a1, a0
; RV64XVENTANACONDOPS-NEXT:    ret
;
; RV64ZICOND-SFB-LABEL: select_t_zero:
; RV64ZICOND-SFB:       # %bb.0:
; RV64ZICOND-SFB-NEXT:    andi a0, a0, 1
; RV64ZICOND-SFB-NEXT:    czero.eqz a0, a1, a0
; RV64ZICOND-SFB-NEXT:    ret
  %r = select i1 %c, i32 %t, i32 0
  ret i32 %r
}

; select c, 0, f
define i32 @select_zero_f(i1 %c, i32 %f) {
; RV32I-LABEL: select_zero_f:
; RV32I:       # %bb.0:
; RV32I-NEXT:    andi a2, a0, 1
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:    bnez a2, .LBB1_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:  .LBB1_2:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: select_zero_f:
; RV64I:       # %bb.0:
; RV64I-NEXT:    andi a2, a0, 1
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:    bnez a2, .LBB1_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:  .LBB1_2:
; RV64I-NEXT:    ret
;
; RV32ZICOND-LABEL: select_zero_f:
; RV32ZICOND:       # %bb.0:
; RV32ZICOND-NEXT:    andi a0, a0, 1
; RV32ZICOND-NEXT:    czero.nez a0, a1, a0
; RV32ZICOND-NEXT:    ret
;
; RV64ZICOND-LABEL: select_zero_f:
; RV64ZICOND:       # %bb.0:
; RV64ZICOND-NEXT:    andi a0, a0, 1
; RV64ZICOND-NEXT:    czero.nez a0, a1, a0
; RV64ZICOND-NEXT:    ret
;
; RV64XVENTANACONDOPS-LABEL: select_zero_f:
; RV64XVENTANACONDOPS:       # %bb.0:
; RV64XVENTANACONDOPS-NEXT:    andi a0, a0, 1
; RV64XVENTANACONDOPS-NEXT:    vt.maskcn a0, a1, a0
; RV64XVENTANACONDOPS-NEXT:    ret
;
; RV64ZICOND-SFB-LABEL: select_zero_f:
; RV64ZICOND-SFB:       # %bb.0:
; RV64ZICOND-SFB-NEXT:    andi a0, a0, 1
; RV64ZICOND-SFB-NEXT:    czero.nez a0, a1, a0
; RV64ZICOND-SFB-NEXT:    ret
  %r = select i1 %c, i32 0, i32 %f
  ret i32 %r
}

; select c, t, f
define i32 @select_general(i1 %c, i32 %t, i32 %f) {
; RV32I-LABEL: select_general:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mv a3, a0
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    andi a3, a3, 1
; RV32I-NEXT:    bnez a3, .LBB2_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:  .LBB2_2:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: select_general:
; RV64I:       # %bb.0:
; RV64I-NEXT:    mv a3, a0
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    andi a3, a3, 1
; RV64I-NEXT:    bnez a3, .LBB2_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:  .LBB2_2:
; RV64I-NEXT:    ret
;
; RV32ZICOND-LABEL: select_general:
; RV32ZICOND:       # %bb.0:
; RV32ZICOND-NEXT:    andi a0, a0, 1
; RV32ZICOND-NEXT:    czero.eqz a1, a1, a0
; RV32ZICOND-NEXT:    czero.nez a0, a2, a0
; RV32ZICOND-NEXT:    or a0, a1, a0
; RV32ZICOND-NEXT:    ret
;
; RV64ZICOND-LABEL: select_general:
; RV64ZICOND:       # %bb.0:
; RV64ZICOND-NEXT:    andi a0, a0, 1
; RV64ZICOND-NEXT:    czero.eqz a1, a1, a0
; RV64ZICOND-NEXT:    czero.nez a0, a2, a0
; RV64ZICOND-NEXT:    or a0, a1, a0
; RV64ZICOND-NEXT:    ret
;
; RV64XVENTANACONDOPS-LABEL: select_general:
; RV64XVENTANACONDOPS:       # %bb.0:
; RV64XVENTANACONDOPS-NEXT:    andi a0, a0, 1
; RV64XVENTANACONDOPS-NEXT:    vt.maskc a1, a1, a0
; RV64XVENTANACONDOPS-NEXT:    vt.maskcn a0, a2, a0
; RV64XVENTANACONDOPS-NEXT:    or a0, a1, a0
; RV64XVENTANACONDOPS-NEXT:    ret
;
; RV64ZICOND-SFB-LABEL: select_general:
; RV64ZICOND-SFB:       # %bb.0:
; RV64ZICOND-SFB-NEXT:    mv a3, a0
; RV64ZICOND-SFB-NEXT:    mv a0, a1
; RV64ZICOND-SFB-NEXT:    andi a3, a3, 1
; RV64ZICOND-SFB-NEXT:    bnez a3, .LBB2_2
; RV64ZICOND-SFB-NEXT:  # %bb.1:
; RV64ZICOND-SFB-NEXT:    mv a0, a2
; RV64ZICOND-SFB-NEXT:  .LBB2_2:
; RV64ZICOND-SFB-NEXT:    ret
  %r = select i1 %c, i32 %t, i32 %f
  ret i32 %r
}

; eq a, b: the compare folds into the condition operand (czero.nez t, a ^ b)
define i32 @select_eq_ab(i32 %a, i32 %b, i32 %t) {
; RV32I-LABEL: select_eq_ab:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mv a3, a0
; RV32I-NEXT:    mv a0, a2
; RV32I-NEXT:    beq a3, a1, .LBB3_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:  .LBB3_2:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: select_eq_ab:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a3, a0
; RV64I-NEXT:    sext.w a1, a1
; RV64I-NEXT:    mv a0, a2
; RV64I-NEXT:    beq a3, a1, .LBB3_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:  .LBB3_2:
; RV64I-NEXT:    ret
;
; RV32ZICOND-LABEL: select_eq_ab:
; RV32ZICOND:       # %bb.0:
; RV32ZICOND-NEXT:    xor a0, a0, a1
; RV32ZICOND-NEXT:    czero.nez a0, a2, a0
; RV32ZICOND-NEXT:    ret
;
; RV64ZICOND-LABEL: select_eq_ab:
; RV64ZICOND:       # %bb.0:
; RV64ZICOND-NEXT:    sext.w a0, a0
; RV64ZICOND-NEXT:    sext.w a1, a1
; RV64ZICOND-NEXT:    xor a0, a0, a1
; RV64ZICOND-NEXT:    czero.nez a0, a2, a0
; RV64ZICOND-NEXT:    ret
;
; RV64XVENTANACONDOPS-LABEL: select_eq_ab:
; RV64XVENTANACONDOPS:       # %bb.0:
; RV64XVENTANACONDOPS-NEXT:    sext.w a0, a0
; RV64XVENTANACONDOPS-NEXT:    sext.w a1, a1
; RV64XVENTANACONDOPS-NEXT:    xor a0, a0, a1
; RV64XVENTANACONDOPS-NEXT:    vt.maskcn a0, a2, a0
; RV64XVENTANACONDOPS-NEXT:    ret
;
; RV64ZICOND-SFB-LABEL: select_eq_ab:
; RV64ZICOND-SFB:       # %bb.0:
; RV64ZICOND-SFB-NEXT:    sext.w a0, a0
; RV64ZICOND-SFB-NEXT:    sext.w a1, a1
; RV64ZICOND-SFB-NEXT:    xor a0, a0, a1
; RV64ZICOND-SFB-NEXT:    czero.nez a0, a2, a0
; RV64ZICOND-SFB-NEXT:    ret
  %c = icmp eq i32 %a, %b
  %r = select i1 %c, i32 %t, i32 0
  ret i32 %r
}

; ne x, 0: the operand is used directly as the condition
define i32 @select_ne_zero(i32 %x, i32 %t) {
; RV32I-LABEL: select_ne_zero:
; RV32I:       # %bb.0:
; RV32I-NEXT:    mv a2, a0
; RV32I-NEXT:    mv a0, a1
; RV32I-NEXT:    bnez a2, .LBB4_2
; RV32I-NEXT:  # %bb.1:
; RV32I-NEXT:    li a0, 0
; RV32I-NEXT:  .LBB4_2:
; RV32I-NEXT:    ret
;
; RV64I-LABEL: select_ne_zero:
; RV64I:       # %bb.0:
; RV64I-NEXT:    sext.w a2, a0
; RV64I-NEXT:    mv a0, a1
; RV64I-NEXT:    bnez a2, .LBB4_2
; RV64I-NEXT:  # %bb.1:
; RV64I-NEXT:    li a0, 0
; RV64I-NEXT:  .LBB4_2:
; RV64I-NEXT:    ret
;
; RV32ZICOND-LABEL: select_ne_zero:
; RV32ZICOND:       # %bb.0:
; RV32ZICOND-NEXT:    czero.eqz a0, a1, a0
; RV32ZICOND-NEXT:    ret
;
; RV64ZICOND-LABEL: select_ne_zero:
; RV64ZICOND:       # %bb.0:
; RV64ZICOND-NEXT:    sext.w a0, a0
; RV64ZICOND-NEXT:    czero.eqz a0, a1, a0
; RV64ZICOND-NEXT:    ret
;
; RV64XVENTANACONDOPS-LABEL: select_ne_zero:
; RV64XVENTANACONDOPS:       # %bb.0:
; RV64XVENTANACONDOPS-NEXT:    sext.w a0, a0
; RV64XVENTANACONDOPS-NEXT:    vt.maskc a0, a1, a0
; RV64XVENTANACONDOPS-NEXT:    ret
;
; RV64ZICOND-SFB-LABEL: select_ne_zero:
; RV64ZICOND-SFB:       # %bb.0:
; RV64ZICOND-SFB-NEXT:    sext.w a0, a0
; RV64ZICOND-SFB-NEXT:    czero.eqz a0, a1, a0
; RV64ZICOND-SFB-NEXT:    ret
  %c = icmp ne i32 %x, 0
  %r = select i1 %c, i32 %t, i32 0
  ret i32 %r
}
