; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -global-isel -mattr=+zfhmin,+d -verify-machineinstrs \
; RUN:   -target-abi=ilp32d < %s | FileCheck -check-prefix=RV32 %s
; RUN: llc -mtriple=riscv64 -global-isel -mattr=+zfhmin,+d -verify-machineinstrs \
; RUN:   -target-abi=lp64d < %s | FileCheck -check-prefix=RV64 %s

; With Zfhmin the half<->float/double conversions are legal and selected by
; GlobalISel instead of falling back to SelectionDAG.

define float @fpext_h_s(half %a) nounwind {
; RV32-LABEL: fpext_h_s:
; RV32:       # %bb.0:
; RV32-NEXT:    fcvt.s.h fa0, fa0
; RV32-NEXT:    ret
;
; RV64-LABEL: fpext_h_s:
; RV64:       # %bb.0:
; RV64-NEXT:    fcvt.s.h fa0, fa0
; RV64-NEXT:    ret
  %1 = fpext half %a to float
  ret float %1
}

define double @fpext_h_d(half %a) nounwind {
; RV32-LABEL: fpext_h_d:
; RV32:       # %bb.0:
; RV32-NEXT:    fcvt.d.h fa0, fa0
; RV32-NEXT:    ret
;
; RV64-LABEL: fpext_h_d:
; RV64:       # %bb.0:
; RV64-NEXT:    fcvt.d.h fa0, fa0
; RV64-NEXT:    ret
  %1 = fpext half %a to double
  ret double %1
}

define half @fptrunc_s_h(float %a) nounwind {
; RV32-LABEL: fptrunc_s_h:
; RV32:       # %bb.0:
; RV32-NEXT:    fcvt.h.s fa0, fa0
; RV32-NEXT:    ret
;
; RV64-LABEL: fptrunc_s_h:
; RV64:       # %bb.0:
; RV64-NEXT:    fcvt.h.s fa0, fa0
; RV64-NEXT:    ret
  %1 = fptrunc float %a to half
  ret half %1
}

define half @fptrunc_d_h(double %a) nounwind {
; RV32-LABEL: fptrunc_d_h:
; RV32:       # %bb.0:
; RV32-NEXT:    fcvt.h.d fa0, fa0
; RV32-NEXT:    ret
;
; RV64-LABEL: fptrunc_d_h:
; RV64:       # %bb.0:
; RV64-NEXT:    fcvt.h.d fa0, fa0
; RV64-NEXT:    ret
  %1 = fptrunc double %a to half
  ret half %1
}
