; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I
; RUN: llc -mtriple=riscv64 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I
; RUN: llc -mtriple=riscv32 -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV32I-GISEL
; RUN: llc -mtriple=riscv64 -global-isel -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=RV64I-GISEL

@addr = global ptr null

define void @test_blockaddress() nounwind {
; RV32I-LABEL: test_blockaddress:
; RV32I:       # %bb.0:
; RV32I-NEXT:    lui a0, %hi(addr)
; RV32I-NEXT:    lui a1, %hi(.Ltmp0)
; RV32I-NEXT:    addi a1, a1, %lo(.Ltmp0)
; RV32I-NEXT:    sw a1, %lo(addr)(a0)
; RV32I-NEXT:    lw a0, %lo(addr)(a0)
; RV32I-NEXT:    jr a0
; RV32I-NEXT:  .Ltmp0: # Block address taken
; RV32I-NEXT:  .LBB0_1: # %block
; RV32I-NEXT:    ret
;
; RV64I-LABEL: test_blockaddress:
; RV64I:       # %bb.0:
; RV64I-NEXT:    lui a0, %hi(addr)
; RV64I-NEXT:    lui a1, %hi(.Ltmp0)
; RV64I-NEXT:    addi a1, a1, %lo(.Ltmp0)
; RV64I-NEXT:    sd a1, %lo(addr)(a0)
; RV64I-NEXT:    ld a0, %lo(addr)(a0)
; RV64I-NEXT:    jr a0
; RV64I-NEXT:  .Ltmp0: # Block address taken
; RV64I-NEXT:  .LBB0_1: # %block
; RV64I-NEXT:    ret
;
; RV32I-GISEL-LABEL: test_blockaddress:
; RV32I-GISEL:       # %bb.0:
; RV32I-GISEL-NEXT:    lui a0, %hi(.Ltmp0)
; RV32I-GISEL-NEXT:    addi a0, a0, %lo(.Ltmp0)
; RV32I-GISEL-NEXT:    lui a1, %hi(addr)
; RV32I-GISEL-NEXT:    sw a0, %lo(addr)(a1)
; RV32I-GISEL-NEXT:    lw a0, %lo(addr)(a1)
; RV32I-GISEL-NEXT:    jr a0
; RV32I-GISEL-NEXT:  .Ltmp0: # Block address taken
; RV32I-GISEL-NEXT:  .LBB0_1: # %block
; RV32I-GISEL-NEXT:    ret
;
; RV64I-GISEL-LABEL: test_blockaddress:
; RV64I-GISEL:       # %bb.0:
; RV64I-GISEL-NEXT:    lui a0, %hi(.Ltmp0)
; RV64I-GISEL-NEXT:    addi a0, a0, %lo(.Ltmp0)
; RV64I-GISEL-NEXT:    lui a1, %hi(addr)
; RV64I-GISEL-NEXT:    sd a0, %lo(addr)(a1)
; RV64I-GISEL-NEXT:    ld a0, %lo(addr)(a1)
; RV64I-GISEL-NEXT:    jr a0
; RV64I-GISEL-NEXT:  .Ltmp0: # Block address taken
; RV64I-GISEL-NEXT:  .LBB0_1: # %block
; RV64I-GISEL-NEXT:    ret
  store volatile ptr blockaddress(@test_blockaddress, %block), ptr @addr
  %val = load volatile ptr, ptr @addr
  indirectbr ptr %val, [label %block]

block:
  ret void
}
